# PHP CircleCI 2.0 configuration file
#
version: 2
jobs:
  build:
    machine: true
    working_directory: ~/work
    steps:
      - checkout
      - run:
          name: Start docker containers.
          command: |
            set -x
            docker-compose up -d
      - deploy:
          name: Deploy Over SSH.
          command: |
            scp -r ~/work/. $SSH_USER@$SSH_HOST:/home/$/web/$PROJECT/.
